### ISSUE TITLE
Need a server account to deploy the app

### ISSUE THREAD

**Issue by chenblair** [MobileCommerceLab/basic_ionic_channels_chat#1]
Currently, the SOCKET_URL given is a `localhost:8000`, so the chat app only works on my personal laptop since the "server" is a local Docker container.

@drspangle should set up a server account so I can deploy a websocket server online so that chat app actually works between different devices.

**Comment by chenblair** [comment]
My andrewID is blairc

**Comment by drspangle** [comment]
This has been set up. Closing.
