### ISSUE TITLE
Dependency Vulnerability

### ISSUE THREAD

**Issue by drspangle** [MobileCommerceLab/basic_ionic_channels_chat#2]
![image](https://user-images.githubusercontent.com/2737227/40284266-81c1b37c-5c5a-11e8-97a6-cdab2e3d4c28.png)

@chenblair Can you update to the version which isn't vulnerable? Shouldn't be too tough.

**Comment by chenblair** [comment]
Fixed, package `hoek` has been updated in https://github.com/MobileCommerceLab/basic_ionic_channels_chat/commit/840ef2e845f6306e05a6cc06e555826e6ca93ee6
