### ISSUE TITLE
Adhere to the Mobile Commerce Lab Software Development Requirements

### ISSUE THREAD

**Issue by chenblair** [MobileCommerceLab/basic_ionic_channels_chat#3]
Per the Mobile Commerce Lab Software Development Requirements, this repo should have:

- [x] Copyright notices
- [x] README file explaining the project at a high level
- [x] Basic documentation so that someone completely unfamiliar can set up the project
- [x] Internal code documentation

After these conditions are satisfied, the master branch should be protected so that reviewed pull requests are required.

**Comment by drspangle** [comment]
I already protected the master branch, but I'll expedite the review of any
PRs to address this issue.

**Comment by chenblair** [comment]
Closing issue.

Proper documentation and changes were made at https://github.com/MobileCommerceLab/basic_ionic_channels_chat/commit/81f917b0cc5297c9ff80da88bb85688bf7adf66e
