### ISSUE TITLE
Add Server Side code in separate repo

### ISSUE THREAD

**Issue by chenblair** [MobileCommerceLab/basic_ionic_channels_chat#7]
As per #6 and the Software requirements, the server side code making the chat app work should be added in a separate repository.

**Comment by drspangle** [comment]
@chenblair You can link to the repo here when that's done, and close the issue at that time.

**Comment by chenblair** [comment]
Repo has been created: https://github.com/MobileCommerceLab/basic_channels_chat_server

Closing.
